apiVersion: apps/v1
kind: Deployment
metadata:
  name: diplom-app
  namespace: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diplom-app
  template:
    metadata:
      labels:
        app: diplom-app
    spec:
      containers:
      - name: diplom-app-container
        image: alexgavaz/diplom-app:${TAG_IMAGE}
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: diplom-service
  namespace: master
  annotations:
    service.beta.kubernetes.io/yandex-load-balancer-healthcheck-timeout: "5s"
    service.beta.kubernetes.io/yandex-load-balancer-healthcheck-interval: "10s"
    service.beta.kubernetes.io/yandex-load-balancer-healthcheck-healthy-threshold: "2"
    service.beta.kubernetes.io/yandex-load-balancer-healthcheck-unhealthy-threshold: "2"
    service.beta.kubernetes.io/yandex-load-balancer-healthcheck-port: "80"
    service.beta.kubernetes.io/yandex-load-balancer-type: "external"
spec:
  selector:
    app: diplom-app
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
